---
title: "linguistics_final"
author: "b06303009"
date: "2021-Feb-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(showtext)
library(ggrepel)
options(stringsAsFactors = F)
options(verbose = T)
options(scipen = 999)
```

```{r}
data_all <- read_csv("~/Courses/linguistics/quantifier/all.csv")
data_v1 <-  read_csv("~/Courses/linguistics/quantifier/V1.csv")
data_v2 <-  read_csv("~/Courses/linguistics/quantifier/V2.csv")
```

# 雙對副

```{r}
temp_1 <- data_v1 %>%
  filter(is.na(`請問你接觸、學習中文幾年了呢，請以數字作答（ex. 1.5、6）？`)) %>%
  filter(`請問你是中文母語使用者嗎？` == "是") %>%
  select(-Zeitstempel,
         -`聯絡方式（ex. Email or FB or IG or Line or 手機號碼）`,
         -`請問你是中文母語使用者嗎？`,
         -`請問你接觸、學習中文幾年了呢，請以數字作答（ex. 1.5、6）？`) %>%
  gather(key="cat", value="quantifier") %>%
  group_by(cat) %>%
  count(quantifier) %>%
  spread(quantifier, n, fill = 0) %>%
  select("item"=cat,
         "fu"=副,
         "dui"=對,
         "shuang"=雙) %>%
  mutate(item = if_else(str_length(item)>5,
						str_extract(item, "\\[.+\\]") %>% str_remove_all("[\\[\\]]"),
						str_c("[",item,"]"))) %>%
  mutate(mm = if_else(max(fu,dui,shuang)==fu,"fu",
                      if_else(max(fu,dui,shuang)==dui,"dui","shuang"))) %>%
  ungroup()
```

```{r}
plot_1 <- temp_1 %>%
  mutate(temp_total = fu + dui + shuang) %>%
  mutate(fu = fu/temp_total,
         dui = dui/temp_total,
         shuang = shuang/temp_total) %>%
  mutate(mm = if_else(mm=="dui","對",if_else(mm=="shuang","雙","副"))) %>%
  ggplot() + aes(x=dui, y=shuang, label=item, color=mm) +
  geom_text_repel(family="Noto Sans CJK KR", max.overlaps = 40) +
  geom_point() +
  # geom_text(family="Noto Sans CJK KR") +
  labs(color="最多人選什麼？",
       title="「 雙對副」量詞類分群 (有\"[]\"的是圖片)",
       x="對",
       y="雙") +
  theme(text = element_text(family = 'Noto Sans CJK KR'))

plot_1
ggsave("plot_1.pdf", plot=plot_1, device=cairo_pdf)
```

# 條根支

```{r}
temp_2 <- data_v2 %>%
  filter(is.na(`請問你接觸、學習中文幾年了呢，請以數字作答（ex. 1.5、6）？`)) %>%
  filter(`請問你是中文母語使用者嗎？` == "是") %>%
  select(-Zeitstempel,
         -`聯絡方式（ex. Email or FB or IG or Line or 手機號碼）`,
         -`請問你是中文母語使用者嗎？`,
         -`請問你接觸、學習中文幾年了呢，請以數字作答（ex. 1.5、6）？`) %>%
  gather(key="cat", value="quantifier") %>%
  group_by(cat) %>%
  count(quantifier) %>%
  spread(quantifier, n, fill = 0) %>%
  select("item"=cat,
         "tiao"=條,
         "gen"=根,
         "zhi"=支) %>%
  mutate(item = if_else(str_length(item)>5,
						str_extract(item, "\\[.+\\]") %>% str_remove_all("[\\[\\]]"),
						str_c("[",item,"]"))) %>%
  mutate(mm = if_else(max(tiao,gen,zhi)==tiao,"tiao",
                      if_else(max(tiao,gen,zhi)==gen,"gen","zhi"))) %>%
  ungroup()
```

```{r}
plot_2 <- temp_2 %>%
  mutate(temp_total = tiao + gen + zhi) %>%
  mutate(tiao = tiao/temp_total,
         gen = gen/temp_total,
         zhi = zhi/temp_total) %>%
  mutate(mm = if_else(mm=="tiao","條",if_else(mm=="gen","根","支"))) %>%
  ggplot() + aes(x=tiao, y=gen, label=item, color=mm) +
  geom_text_repel(family="Noto Sans CJK KR", max.overlaps = 40) +
  geom_point() +
  # geom_text(family="Noto Sans CJK KR") +
  labs(color="最多人選什麼？",
       title="「 條根支」量詞類分群 (有\"[]\"的是圖片)",
       x="條",
       y="根") +
  theme(text = element_text(family = 'Noto Sans CJK KR'))

plot_2
set terminal png size 1024,1024
ggsave("plot_2.pdf", plot=plot_2, device=cairo_pdf)
```
